language: objective-c
osx_image: xcode7
before_script:
# - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/Hello_World.mobileprovision.enc -d -a -out scripts/profile/Hello_World.mobileprovision
# - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a -out scripts/certs/dist.cer
# - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a -out scripts/certs/dist.p12
- "./scripts/add-key.sh"
script:
- xctool -workspace Hello-World.xcworkspace -scheme Hello-World -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO 'CODE_SIGN_RESOURCE_RULES_PATH=$(SDKROOT)/ResourceRules.plist'
env:
  global:
  - APP_NAME="Hello-World"
  - 'DEVELOPER_NAME="iPhone Distribution: Datacom (3W2D35BGJW)"'
  - PROFILE_NAME="Hello_World"
  - secure: QF0sNonnkQArGsu5Wlt9zSB9DhNfEUjsC2ocvdx0hJS18tI9Myv23V2xrYgi49WI5ZYOXTTNFwf+fGfkIs+mVenGB3KcLYhChUzxsRSMMCAagdeL03qxDICMMQzeZSsUuMal41LWQhwqEoQ7GS0TG+dxi2l9OLSCYSdH/EMIqaZDSdRRxsIm8b5SDq1/4Ss9hSIPfGJlZ/gwAZXHw9y1znQ6SXp1T4GhsaGhGFGsWcb7WTDwpQJNmeoZdlxlr/jrQQaRnmgKBv5w9ClHfNGPjv3/zYpWkRF+LlOERE4E4rur/xnZUOC1cC5zv0imZhuevA9LNOpxIk4s5H1H7SeWysgpcbS9QK4t6ecNrxywkF/Wgwt6Ies7/js0PFW8iOqrueiFHqMy3yBUmvjNi5/PHsi8F7o8KaREFydHUt/+LWP+PCklKjZHrapgz2O48fW9dcn08VO0OkZwgnSdHFndV5J3/GwwHQ3wylmUN9GJ65BDHYNv+KwxEKB7wkzAzD/pdeKWfooTeDBn9x8Wvd7SLRQMOOivLNEkD6nFhxQ9aQDAnzBvyqJ9m01mmmLe2VRUT6q/W0xstPoUgYfROtFoHoSBxV2z1OL4TS+XFncNnz2tzveI912kdIvp3sb/EbcMd+RcOIf9CDhRM2Hxvupn6MK2aCWHS0OR0yPETYhtqTA=
  - secure: LP9qeUJF/K4xnYuu+tPi5TV3/9hcw3hkyyV8jolKoQcNQJr+ekivdQc3Cxc4HWchGVoSkUfBGXj+qPxX5zz5DGptUcNe/LXDRsL01ghUpH12N5jFlRnJxvdNB94jf3UARlMkULaYBN3TqmGpxxwcOjAhIqKn5xxxGCiY0woUxwDGvkY1tmKujkEBt9q3lpyVc0hycuT39T+NNIvr8LHE8jQnYFiUfDICrGLy92WvElJMGjjp9YxMZC8gr7YSBOPZrz9E7CYKqn0Db4bWkgmhH+9fi4ZMEvxryAmo+NKaQAOQZitwFo+mdGlALvVbZ4J0Dbf1g120yYKdLaPEAduYDAQOK6aC5ScPTQCgxbl+WqrJz2nF52EgjRPvuVNhPXlfgyTXxv3d4E18OUkcRoPzuKdt+IphmJ9wR1aedetP8YYSIzYnxr6ak269MDsCKLmCZZKx9GxKmy7w2KGDLK+cYKSlcct8vvgSI+jQtpIM9EANFKYVHPFiM+PM3UXetvotYm8Uudj0pvk+B0UPq/Ke07a9iIz3lSgXf7omB6u/6T5VorIIkRtrAReG+vKV6KkR1jRNz4mr87+Rjz9hf/yM0BORAUjDndT9op9GLnE931q6EdlDkYWv2coYG1oLT+wU1YGSdUG3BlreRN3/nYfKB4RTMaOkuPG0gdr3Z+jyzaw=
after_success:
- "./scripts/sign-and-upload.sh"
after_script:
- "./scripts/remove-key.sh"
