language: objective-c
osx_image: xcode7
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/Hello_World.mobileprovision.enc -d -a -out scripts/profile/Hello_World.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a -out scripts/certs/dist.p12
- pod install
- "./scripts/add-key.sh"
script:
- xctool -workspace Hello-World.xcworkspace -scheme Hello-World -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO 'CODE_SIGN_RESOURCE_RULES_PATH=$(SDKROOT)/ResourceRules.plist'
- xctool -workspace Hello-World.xcworkspace -scheme Hello-World clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
env:
  global:
  - APP_NAME="Hello-World"
  - 'DEVELOPER_NAME="iPhone Distribution: Datacom (3W2D35BGJW)"'
  - PROFILE_NAME="Hello_World"
  - secure: Xvt5mCwaEraDfw68HT4944XJeM4volVdmnMHd3sJ5dV5DtxPEEjekqE9b+ZmefmUxbZ/IwxO8p4hZNBIPIVEi2cypnSz2I/L7/rIxOpRm44aIBwpczOdQCzyLfQicgpQ3iwMbUTyZMfxKgZAWcbzYuLwbs1CnJE5J7Co0h4XgM0ux3OzSdsUJGSG8JG8BPNq/dWXTSaULDTjx7l4I6GG2bB29TFjoqNjLahK9HT6UYS0kc5/ZAvNUYNXCAOj1c/8PU05zsqKM2+Jb3Qtk2H0Ze5C/sMTncbomJ27UsBzhoLVNjkBFwI4zqoCYVUJNB7hDCNKfxWsO79G4F6dIUYGOcRPKP1TSNjIdD90dVRt9ql6rq8WmHMfpBuQdmtCCpmUqMFHpsjw/najaJChyARD/jg+5lWzmt4CMuq1rRLacUkBVsUHCPoxi+9bUpiVwJ0EIcsfm+esSDRALCtSk71r2cBwr3wQ/c1YTXONhi1XhgTwhlEcZcKFwFclvKAMEoV4xcmXgvE24mEJoa+FO+PFUAKxsUa/FLMNYRZ0+GGxCg38yO2HQwGqVlou3XrTOmKvQ6VLM/0Eo1YtclKjG/tmI14zPFWLPq2mulfAdDlr3DaY4Bl6qLXpFxhQZjOAHptN/y2NYfJ5jejb1tcPJXd8yGFg8tGeco6dqpc5iz/DuiU=
  - secure: KfVf7eSyrrNBQAi9N1ewZ4ooDMk+O4MhUCXyO9bNz3Qg3BaTcGm72U6oRMORqw9OJhzG8F08M/F1MtYD38FKoFHLwXK5SVc5DE37OKu4d9s/M1RDK480o9MpYPWnh7nRPWb5D5Fu6NjPx33CR3hHKsBVoimBpryucreINKGregMT0fVcyYGK82W5jLeXDMS2oWvHq2+l1UZWz9ExJTUGa3hXVRDhllOYtcAgSzFfVb4UsrmifU+F8sCE/vM0RWizowEKr0M3M1/SxmQr8i2zau1R+GQKI5E9IDx16yiYxJHbbt71iJKYvFPc06LHcbEpMgyIFzb42zu7H/KxngRYReE0brkuIYrg3BhF6M1pRaPDHSUz60UJhMSlfxHVdiEyhho+PSrvew+LL5FVCp73H/k0a6dsoXOo+bmiXnQFX3MR6geF7PadBIr6+Hyq0nZPql+T+1+B7hCibJJP9+FkR+m8OYAWdepg54mA9PgLf9zJkkawKDd3Ghwxz7L3AZQk/KIR3cGegK2TBAUr5/5cPvRWbj8R37xZiHoH2orvq8Dk3x11Fqb/xGZCqllYc0qkocoVdIqSSVB7zf7+wfYkGf8UvKNzWx/6GWZFGHHpM6+C6l/PuTGmniv85fsVZCbDev2LPPVUx0H20jz1IzDJZbY55MnZ+PGYCA2k+1W0h1o=
after_success:
- "./scripts/sign-and-upload.sh"
after_script:
- "./scripts/remove-key.sh"
